# Generated by Django 5.2 on 2026-07-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.CharField(max_length=200)),
                (
                    "fecha_publicacion",
                    models.DateTimeField(verbose_name="date published"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Opcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_opcion", models.CharField(max_length=200)),
                ("votos", models.IntegerField(default=0)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="encuestas.pregunta",
                    ),
                ),
            ],
        ),
    ]
