# Generated by Django 5.2 on 2026-07-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pregunta",
            name="fecha_publicacion",
        ),
    ]
